var chapters= [
    {"id": 0,"title":"Select a chapter"},
    {"id": 1,"title":"Ch01 All you need is Lambda"},
    {"id": 2,"title":"Ch02 Hello Haskell"},
    {"id": 3,"title":"Ch03 Strings"},
    {"id": 4,"title":"Ch04 Basic datatypes"},
    {"id": 5,"title":"Ch05 Types"},
    {"id": 6,"title":"Ch06 Typeclasses"},
    {"id": 7,"title":"Ch07 More functional patterns"},
    {"id": 8,"title":"Ch08 Recursion"},
    {"id": 9,"title":"Ch09 Lists"},
    {"id": 10,"title":"Ch10 Folding lists"},
    {"id": 11,"title":"Ch11 Algebraic datatypes"},
    {"id": 12,"title":"Ch12 Signaling adversity"},
    {"id": 13,"title":"Ch13 Building projects"},
    {"id": 14,"title":"Ch14 Testing"},
    {"id": 15,"title":"Ch15 Monoid, Semigroup"},
    {"id": 16,"title":"Ch16 Functor "},
    {"id": 17,"title":"Ch17 Applicative"},
    {"id": 18,"title":"Ch18 Monad "},
    {"id": 19,"title":"Ch19 Applying structure"},
    {"id": 20,"title":"Ch20 Foldable"},
    {"id": 21,"title":"Ch21 Traversable"},
    {"id": 22,"title":"Ch22 Reader"},
    {"id": 23,"title":"Ch23 State"},
    {"id": 24,"title":"Ch24 Parser combinators"},
    {"id": 25,"title":"Ch25 Composing types"},
    {"id": 26,"title":"Ch26 Monad transformers"},
    {"id": 27,"title":"Ch27 Nonstrictness"},
    {"id": 28,"title":"Ch28 Basic libraries"},
    {"id": 29,"title":"Ch29 IO"},
    {"id": 30,"title":"Ch30 When things go wrong"},
    {"id": 31,"title":"Ch31 Final project"}
]

module.exports = chapters
